spring:
  application:
    name: api-server
  profiles:
    active: dev, dev-mail
  config:
    import: optional:file:.env
  datasource:
    primary:
      jdbc-url: jdbc:postgresql://127.0.0.1:15610/nf-master
      username: nextframe
      password: bySjnb5LeeytlDg
      driver-class-name: org.postgresql.Driver

  #    replica:
  #      jdbc-url: jdbc:postgresql://localhost:5432/read_db
  #      username: user2
  #      password: pass2
  #      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

LOG_LEVEL: DEBUG
ROOT_LOG_LEVEL: ERROR
LOG_PATH_NAME: ${user.home}/logs/backend/dev/performance
LOG_FILE_NAME: performance-api

logging:
  pattern:
    console: '%d %clr([%-5level]) %replace(%caller{1}){"Caller\+\d at ",""}%msg%n'
    file: "%d [%-5level] [%thread] [%c{25}] [%method] %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 60
      total-size-cap: 1GB
  level:
    root: ${ROOT_LOG_LEVEL}
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    wisoft.nextframe: ${LOG_LEVEL}
  file:
    name: ${LOG_PATH_NAME}/${LOG_FILE_NAME}.log

cors:
  allowed-origins: "http://localhost:5173"