spring:
  application:
    name: api-server
  config:
    import: optional:file:.env[.properties]
  datasource:
    primary:
      jdbc-url: jdbc:postgresql://127.0.0.1:15610/nf-master
      username: ${PR_DB_USERNAME}
      password: ${PR_DB_PASSWORD}
      driver-class-name: org.postgresql.Driver

  #    replica:
  #      jdbc-url: jdbc:postgresql://localhost:5432/read_db
  #      username: user2
  #      password: pass2
  #      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE